name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    # ⚠️ Consider moving these to GitHub Secrets and reference them via ${{ secrets.YOUR_NAME }}
    env:
      CI: false
      REACT_APP_PE_CLIENT_ID: 3ba8024cd6f34e83b642f1d287791ff3
      REACT_APP_PE_CLIENT_SECRET: H8a/mwfnQ4F0Tm5pxMimapah9KgzidMuaVD5Dga3fhI=

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      # ⬇️ NEW: Pre-install API deps so we can skip Oryx API build safely
      - name: Use Node 20 for Azure Functions API
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: api/package-lock.json

      - name: Install API dependencies (production)
        working-directory: api
        run: npm ci --omit=dev

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_FLOWER_0CC65E70F }}
          action: "upload"

          # App
          app_location: "./client"
          output_location: "build"

          # API (use relative path + skip API build to avoid Oryx CDN)
          api_location: "./api"
          skip_api_build: true

          # Config
          github_id_token: ${{ steps.idtoken.outputs.result }}
          config_file_location: "."

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
